### PR TITLE
Delete message and moderate chat

### PR DESCRIPTION
**Pull request by HURDOO**
Added some features.

- ```YoutubeLiveChat#setUserData(String SAPISID, String HSID, String SSID, String APISID, String SID, String LOGIN_INFO)```
LOGIN_INFO cookie contains information about current channel. An account can have multiple channels.

- ```YoutubeLiveChat#setUserData(String cookies)```
You can easily put cookies with this. Cookies can be found in Chrome Devtools 'Network' tab (`get_live_chat` request). Other cookies that aren't needed are ignored.

- ```ChatItem#delete()```
Deletes chat.

- ```ChatItem#timeoutAuthor()```
Timeout chat's author (5 min)
- ```ChatItem#banAuthor()```
Ban chat's author
- ```ChatItem#pinAsBanner()```
Pin chat as banner to the top.

### CODE REVIEW

**Comment by kusaanko** [comment]
Thank you for your great commits!
I think banning user is dangerous.
If an vicious programmer use it, he can ban all user. Or if a code has a bug, unintentional banning will occur. For example, if a code that detect certain words and ban user who say them has a bug, it may be dangerous.
How do you think about it? It’s very good function, but it may be dangerous. I must believe all developers. Please let me know your opinion.

How about a function that unban user? If you ban all user, you can unban all user.
But this function need to get all banned users. This seems hard.

**Comment by HURDOO** [comment]
That's a great point! I added unban feature for permanent bans.
- ```ChatItem#unbanAuthor()```
A developer can now store the banned ChatItems and unban later if needed.

I agree that banning may be dangerous, but I also agree banning can block unwanted users.
Nightbot and StreamElements cannot join unlisted and private streams. StreamBots doesn't provide APIs.
This could be useful if used properly. Only channel owners and trustworthy managers can use this ban feature.

Meanwhile, it is hard to retrieve all banned users since it needs us to dive into channel settings, which is away from live chat.

**Comment by kusaanko** [comment]
What a fast development like a cheetah! I’ll check codes and merge into main when I’m free. Thank you.

**Comment by HURDOO** [comment]
Thanks 👍 I'll look forward to being merged :)

**Pull request merged**
